In [9]:
import torch

In [57]:
#Creating an empty tensor
x = torch.empty(3,2)
x

tensor([[2.5223e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])

In [65]:
#Creating a rand tensor
x = torch.rand(3,2)
x

tensor([[0.5876, 0.6234],
        [0.4203, 0.6031],
        [0.6814, 0.1725]])

In [70]:
#Creating a tensor with ones
x = torch.ones(3,2, dtype = torch.int)
x

tensor([[1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)

In [102]:
#Addition of two tensors
x = torch.rand(3,2)
y = torch.rand(3,2)
z = x+y
z
"""or"""
#Similar for other operations sub(),mul(),div()
z = torch.add(x,y)
print(z)

#To print an element as an individual item
print(z[2,0].item())

#To view it in different dimensions
print(z.view(2,3))

#To view the correct dimension 
print(z.view(2,-1).size())

#Convert tensors into numpy arrays
y = z.numpy()
print(y,type(y))

#Convert numpy arrays into tensors
import numpy as np
v = np.array([1,2,3,4,5])
print(v)
w = torch.from_numpy(v)
print(w)

tensor([[1.2422, 1.2734],
        [0.8408, 1.0964],
        [0.4856, 0.6490]])
0.48563194274902344
tensor([[1.2422, 1.2734, 0.8408],
        [1.0964, 0.4856, 0.6490]])
torch.Size([2, 3])
[[1.2422497  1.2733896 ]
 [0.8407612  1.0964413 ]
 [0.48563194 0.64898837]] <class 'numpy.ndarray'>
[1 2 3 4 5]
tensor([1, 2, 3, 4, 5])


In [104]:
if torch.cuda.is_available():
    #If gpu is available, this will execute
    device = torch.device('conda')
    x = tensor.ones(5,device = device)
    y = tensor.ones(5)
    y.to(device)
    z = x+y
    print(z.to('cpu'))
else:
    print(False)

False


In [106]:
x = torch.ones(5,requires_grad = True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

In [141]:
x = torch.randn(3,requires_grad = True)
print(x)

y = torch.randn(3,requires_grad = True)
print(y)

z = (x*y).mean()
print(z)

#Backward propagation to create gradient values for x and y
z.backward()
print(x.grad)
print(y.grad)

#Removing the condition -> requires_grad = False
x = x.requires_grad_(False)
"""or"""
x = x.detach()
print(x)

tensor([1.2233, 2.5919, 0.1686], requires_grad=True)
tensor([-0.5808,  0.4780, -1.4180], requires_grad=True)
tensor(0.0964, grad_fn=<MeanBackward0>)
tensor([-0.1936,  0.1593, -0.4727])
tensor([0.4078, 0.8640, 0.0562])
tensor([1.2233, 2.5919, 0.1686])


In [146]:
x = torch.randn(3,requires_grad = True)

for epoch in range(5):
    model_output = x.mean()
    model_output.backward()
    print(x.grad)
    #**Very Important**
    #After every iteration, the gradient values of a variable should be made to 0 else the values would get added up. 
    x.grad.zero_()
    print(x.grad)

tensor([0.3333, 0.3333, 0.3333])
tensor([0., 0., 0.])
tensor([0.3333, 0.3333, 0.3333])
tensor([0., 0., 0.])
tensor([0.3333, 0.3333, 0.3333])
tensor([0., 0., 0.])
tensor([0.3333, 0.3333, 0.3333])
tensor([0., 0., 0.])
tensor([0.3333, 0.3333, 0.3333])
tensor([0., 0., 0.])


In [256]:
import numpy as np

#Forward and Backward passes along with updating weights
X = np.array([1,2,3,4], dtype = np.float32)
Y = np.array([2,4,6,8], dtype = np.float32)

w = np.array([0.1,0.2,0.3,0.4], dtype = np.float32)

def forward(w,x):
    a = []
    for i in range(0,len(X)):
        a.append(X[i]*w[i])
    return a

def loss(y,y_pred):
    return ((y_pred - y)**2).mean()

def gradient(x,y,y_pred):
    
    return (np.dot(2*x,y_pred-y)).mean()

print(f'Prediction before training: = {forward(w,X)}')

learning_rate = 0.01
n_iters = 10

for epoch in range(n_iters):
    y_pred = forward(w,X)
    
    l = loss(Y, y_pred)
    print(l)
    dw = gradient(X,Y, y_pred)
  
    for i in range(0,len(y_pred)):
        w[i] = w[i] - learning_rate*dw
    
    
    if epoch%1 == 0:
        print(f'epoch {epoch+1}: w = {w}, loss = {l}')

print(f'Prediction after training : = {forward(w,X)}')


Prediction before training: = [0.1, 0.4, 0.90000004, 1.6]
20.885
epoch 1: w = [1.1 1.2 1.3 1.4], loss = 20.885000228881836
3.3850002
epoch 2: w = [1.5       1.6       1.6999999 1.8      ], loss = 3.385000228881836
0.5850001
epoch 3: w = [1.66      1.76      1.8599999 1.9599999], loss = 0.5850000977516174
0.13700004
epoch 4: w = [1.724     1.824     1.9239999 2.024    ], loss = 0.13700003921985626
0.06532001
epoch 5: w = [1.7496    1.8496001 1.9496    2.0496   ], loss = 0.06532000750303268
0.05385115
epoch 6: w = [1.7598401 1.8598402 1.95984   2.05984  ], loss = 0.05385114997625351
0.052016087
epoch 7: w = [1.763936  1.8639362 1.9639361 2.063936 ], loss = 0.052016086876392365
0.051722504
epoch 8: w = [1.7655745 1.8655746 1.9655745 2.0655744], loss = 0.05172250419855118
0.051675532
epoch 9: w = [1.7662297 1.8662299 1.9662298 2.0662298], loss = 0.05167553201317787
0.051668093
epoch 10: w = [1.7664919 1.866492  1.9664919 2.0664918], loss = 0.05166809260845184
Prediction after training : = 

In [323]:

#Forward and Backward passes along with updating weights
X = torch.tensor([1,2,3,4], dtype = torch.float32)
Y = torch.tensor([2,4,6,8], dtype = torch.float32)

w = torch.tensor(0.01, dtype = torch.float32, requires_grad = True)

def forward(x):
    return w*x

def loss(y,y_pred):
    return ((y_pred - y)**2).mean()

def gradient(x,y,y_pred):
    
    return (np.dot(2*x,y_pred-y)).mean()

print(f'Prediction before training: f(5) = {forward(5):.3f}')

learning_rate = 0.01
n_iters = 10

for epoch in range(n_iters):
    y_pred = forward(X)
    
    l = loss(Y, y_pred)
    
    #Using backward() function
    l.backward()
    print(w.grad)
    with torch.no_grad():
        w -= learning_rate*w.grad
        
    w.grad.zero_()
    
    if epoch%1 == 0:
        print(f'epoch {epoch+1}: w = {w}, loss = {l}')

print(f'Prediction after training: f(5) = {forward(5):.3f}')


Prediction before training: f(5) = 0.050
tensor(-29.8500)
epoch 1: w = 0.3084999918937683, loss = 29.700748443603516
tensor(-25.3725)
epoch 2: w = 0.5622249841690063, loss = 21.458789825439453
tensor(-21.5666)
epoch 3: w = 0.777891218662262, loss = 15.50397777557373
tensor(-18.3316)
epoch 4: w = 0.9612075090408325, loss = 11.201624870300293
tensor(-15.5819)
epoch 5: w = 1.1170263290405273, loss = 8.09317398071289
tensor(-13.2446)
epoch 6: w = 1.2494723796844482, loss = 5.847318649291992
tensor(-11.2579)
epoch 7: w = 1.3620514869689941, loss = 4.2246880531311035
tensor(-9.5692)
epoch 8: w = 1.457743763923645, loss = 3.052337408065796
tensor(-8.1338)
epoch 9: w = 1.5390821695327759, loss = 2.2053136825561523
tensor(-6.9138)
epoch 10: w = 1.608219861984253, loss = 1.593339204788208
Prediction after training: f(5) = 8.041


In [467]:
#Implementation of Linear Regression

import torch
import torch.nn as nn

X = torch.tensor([[1],[2],[3],[4]], dtype = torch.float32)
Y = torch.tensor([[2],[4],[6],[8]], dtype = torch.float32)

X_test = torch.tensor([5], dtype = torch.float32)

n_samples, n_features = X.shape

input_size = n_features
output_size = n_features 


class LinearRegression(nn.Module):

    def __init__(self,input_dim, output_dim):
        super(LinearRegression,self).__init__()
        self.lin = nn.Linear(input_dim, output_dim)
        
    def forward(self,x):
        return self.lin(x)
    
model = LinearRegression(input_size,output_size)
print(f'Prediction before training : f(5) = {model(X_test).item():.3f}')

#Training
learning_rate = 0.01
n_iters = 10

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)


for epoch in range(n_iters):
    
    #Prediction
    y_pred = model.forward(X)
    
    #loss
    l = loss(Y,y_pred)
    
    #gradients = backward pass
    l.backward()
    
    #update weights
    with torch.no_grad():
        #Using step() function to update weights
        optimizer.step()
    
    #Using zero_grad comman
    optimizer.zero_grad()
    
    print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')
        
print(f'Prediction after training : f(5) = {model(X_test).item():.3f}')

Prediction before training : f(5) = 3.632
epoch 1: w = 0.000, loss = 12.17042923
epoch 2: w = 0.000, loss = 8.45229340
epoch 3: w = 0.000, loss = 5.87231302
epoch 4: w = 0.000, loss = 4.08207512
epoch 5: w = 0.000, loss = 2.83982205
epoch 6: w = 0.000, loss = 1.97780490
epoch 7: w = 0.000, loss = 1.37962627
epoch 8: w = 0.000, loss = 0.96451867
epoch 9: w = 0.000, loss = 0.67644191
epoch 10: w = 0.000, loss = 0.47650814
Prediction after training : f(5) = 8.756


In [466]:
#Implementation of Logistic Regression

import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

bc = datasets.load_breast_cancer()
X,y = bc.data, bc.target

n_samples, n_features = X.shape

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train = torch.from_numpy(X_train.astype(np.float32))
X_test = torch.from_numpy(X_test.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))

y_train = y_train.view(y_train.shape[0],1)
y_test = y_test.view(y_test.shape[0],1)

class LogisticRegression(nn.Module):
    
    def __init__(self,n_input_features):
        super(LogisticRegression,self).__init__()
        self.lin = nn.Linear(n_input_features,1)
        
    def forward(self,x):
        y_predicted = torch.sigmoid(self.lin(x))
        return y_predicted
    
model = LogisticRegression(n_features)

learning_rate = 0.01
criterion = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)

num_epochs = 100
for epoch in range(num_epochs):
    
    y_pred = model(X_train)
    
    loss = criterion(y_pred, y_train)
    
    loss.backward()
    
    optimizer.step()
    
    optimizer.zero_grad()
    
    print(f'epoch : {epoch+1}, loss = {loss.item():.4f}')

with torch.no_grad():
    y_pred = model(X_test)
    y_predicted_cls = y_pred.round()
    acc = y_predicted_cls.eq(y_test).sum()/float(y_test.shape[0])
    print(f'accuracy = {acc:4f}')

epoch : 1, loss = 0.5903
epoch : 2, loss = 0.5777
epoch : 3, loss = 0.5659
epoch : 4, loss = 0.5546
epoch : 5, loss = 0.5440
epoch : 6, loss = 0.5338
epoch : 7, loss = 0.5242
epoch : 8, loss = 0.5151
epoch : 9, loss = 0.5064
epoch : 10, loss = 0.4981
epoch : 11, loss = 0.4902
epoch : 12, loss = 0.4827
epoch : 13, loss = 0.4754
epoch : 14, loss = 0.4685
epoch : 15, loss = 0.4619
epoch : 16, loss = 0.4556
epoch : 17, loss = 0.4495
epoch : 18, loss = 0.4436
epoch : 19, loss = 0.4380
epoch : 20, loss = 0.4326
epoch : 21, loss = 0.4274
epoch : 22, loss = 0.4223
epoch : 23, loss = 0.4175
epoch : 24, loss = 0.4128
epoch : 25, loss = 0.4082
epoch : 26, loss = 0.4039
epoch : 27, loss = 0.3996
epoch : 28, loss = 0.3955
epoch : 29, loss = 0.3916
epoch : 30, loss = 0.3877
epoch : 31, loss = 0.3840
epoch : 32, loss = 0.3803
epoch : 33, loss = 0.3768
epoch : 34, loss = 0.3734
epoch : 35, loss = 0.3700
epoch : 36, loss = 0.3668
epoch : 37, loss = 0.3637
epoch : 38, loss = 0.3606
epoch : 39, loss = 0.

In [476]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

class WineDataset(Dataset):
    
    def __init__(self):
        #data loading
        xy = np.loadtxt('/Users/cassinthangam/Desktop/wine.csv', delimiter = ",", dtype = np.float32, skiprows = 1)
        self.x = torch.from_numpy(xy[:,1:])
        self.y = torch.from_numpy(xy[:,[0]])
        self.n_samples = xy.shape[0]
    
    def __getitem__(self,index):
        return self.x[index], self.y[index]
    
    def __len__(self):
        return self.n_samples
    
dataset = WineDataset()
dataloader = DataLoader(dataset = dataset, batch_size = 4, shuffle = True)

num_epochs = 2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/4)
print(total_samples, n_iterations)

for epoch in range(num_epochs):
    for i, (inputs,labels) in enumerate(dataloader):
        if (i+1)%5 == 0:
            print(f'epoch {epoch+1}/{num_epochs}, step {i+1}/{n_iterations}, inputs {inputs.shape}')


178 45
epoch 1/2, step 5/45, inputs torch.Size([4, 13])
epoch 1/2, step 10/45, inputs torch.Size([4, 13])
epoch 1/2, step 15/45, inputs torch.Size([4, 13])
epoch 1/2, step 20/45, inputs torch.Size([4, 13])
epoch 1/2, step 25/45, inputs torch.Size([4, 13])
epoch 1/2, step 30/45, inputs torch.Size([4, 13])
epoch 1/2, step 35/45, inputs torch.Size([4, 13])
epoch 1/2, step 40/45, inputs torch.Size([4, 13])
epoch 1/2, step 45/45, inputs torch.Size([2, 13])
epoch 2/2, step 5/45, inputs torch.Size([4, 13])
epoch 2/2, step 10/45, inputs torch.Size([4, 13])
epoch 2/2, step 15/45, inputs torch.Size([4, 13])
epoch 2/2, step 20/45, inputs torch.Size([4, 13])
epoch 2/2, step 25/45, inputs torch.Size([4, 13])
epoch 2/2, step 30/45, inputs torch.Size([4, 13])
epoch 2/2, step 35/45, inputs torch.Size([4, 13])
epoch 2/2, step 40/45, inputs torch.Size([4, 13])
epoch 2/2, step 45/45, inputs torch.Size([2, 13])
